GET http://localhost:3000/user-api/users

###
POST http://localhost:3000/user-api/users
Content-Type: application/json

{
    "id":100,
    "name":"shashank",
    "age":20
}


###
PUT http://localhost:3000/user-api/users
Content-Type: application/json

{
    "id":100,
    "name":"shashank reddy",
    "age":21
}


### read a user by id
GET http://localhost:3000/user-api/users/100

###
DELETE http://localhost:3000/user-api/users/100










###
GET http://localhost:3000/product-api/products

###
POST http://localhost:3000/product-api/products
Content-Type: application/json

{
    "productId":100,
    "Name":"laptop",
    "Price":50000,
    "brand":"Dell"
}


###
PUT http://localhost:3000/product-api/products/100
Content-Type:application/json

{
    "productId":100,
    "Name":"laptop",
    "Price":70000,
    "brand":"Dell"
}



### read a product by id
GET http://localhost:3000/product-api/products/product-id/100


### read a product by brand
GET http://localhost:3000/product-api/products/product-brand/laptop



###
DELETE http://localhost:3000/product-api/products/100